/* 打卡名言库：400 句德国谚语/名言，打卡时随机抽取 */
/* 格式：[德文, 中文翻译, 作者]，作者为“德文原名（中文译名）” */
const CHECKIN_QUOTES = [
["Aller Anfang ist schwer.", "万事开头难。", "Deutsches Sprichwort（德国谚语）"],
["Übung macht den Meister.", "熟能生巧。", "Deutsches Sprichwort（德国谚语）"],
["Wer rastet, der rostet.", "谁停歇，谁生锈。（业精于勤荒于嬉。）", "Deutsches Sprichwort（德国谚语）"],
["Ohne Fleiß kein Preis.", "一分耕耘，一分收获。", "Deutsches Sprichwort（德国谚语）"],
["Ende gut, alles gut.", "结局好，一切都好。", "Deutsches Sprichwort（德国谚语）"],
["Wer die Wahl hat, hat die Qual.", "有选择，就有烦恼。（难以抉择。）", "Deutsches Sprichwort（德国谚语）"],
["Reden ist Silber, Schweigen ist Gold.", "开口是银，沉默是金。", "Deutsches Sprichwort（德国谚语）"],
["Morgen, morgen, nur nicht heute! Sprechen immer träge Leute.", "明天，明天，偏偏不是今天！懒人总是这样说。", "Christian Felix Weiße（克里斯蒂安·费利克斯·魏斯）"],
["Aller Anfang ist leicht, und die letzten Stufen werden am schwersten und seltensten erstiegen.", "开头总是容易的，而最后的台阶最难攀登，也最少有人登上。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Lügen haben kurze Beine.", "谎言站不住脚。（谎言腿短。）", "Deutsches Sprichwort（德国谚语）"],
["Probieren geht über Studieren.", "实践出真知。", "Deutsches Sprichwort（德国谚语）"],
["Ein Unglück kommt selten allein.", "祸不单行。", "Deutsches Sprichwort（德国谚语）"],
["Steter Tropfen höhlt den Stein.", "滴水穿石。", "Deutsches Sprichwort（德国谚语）"],
["Taten sagen mehr als Worte.", "事实胜于雄辩。（行动胜于言语。）", "Deutsches Sprichwort（德国谚语）"],
["Aus den Augen, aus dem Sinn.", "离久情疏。（眼不见，心不想。）", "Deutsches Sprichwort（德国谚语）"],
["Jeder ist seines Glückes Schmied.", "命运掌握在自己手中。（每个人都是自己命运的铁匠。）", "Deutsches Sprichwort（德国谚语）"],
["Hunger ist der beste Koch.", "饥饿是最好的厨师。", "Deutsches Sprichwort（德国谚语）"],
["Besser spät als nie.", "迟做总比不做好。", "Deutsches Sprichwort（德国谚语）"],
["Es irrt der Mensch, solang er strebt.", "人只要奋斗，难免会犯错。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Verweile doch! Du bist so schön!", "停一停吧，你真美！", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Hier bin ich Mensch, hier darf ich's sein!", "在这里我是个人，在这里我可以做个人！", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Die Botschaft hör ich wohl, allein mir fehlt der Glaube.", "这消息我固然听到了，只是我缺乏信仰。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Was glänzt, ist für den Augenblick geboren, das Echte bleibt der Nachwelt unverloren.", "闪耀之物只为瞬间而生，真正之物将传之后世。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Willst du immer weiter schweifen? Sieh, das Gute liegt so nah.", "难道你总想去远方流浪？看吧，美好就在身旁。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Anfangen ist leicht, Beharren eine Kunst.", "万事开头易，坚持才是艺术。", "Deutsches Sprichwort（德国谚语）"],
["Die Kunst ist eine Tochter der Freiheit.", "艺术是自由的女儿。", "Friedrich Schiller（弗里德里希·席勒）"],
["Dem Mutigen hilft Gott.", "上帝眷顾勇敢之人。", "Friedrich Schiller（弗里德里希·席勒）"],
["Spät kommt Ihr, doch Ihr kommt!", "您来迟了，但您终究还是来了！", "Friedrich Schiller（弗里德里希·席勒）"],
["Was ist der langen Rede kurzer Sinn?", "这长篇大论的简短主旨是什么？", "Friedrich Schiller（弗里德里希·席勒）"],
["Der Mensch ist frei geschaffen, ist frei, und würd er in Ketten geboren.", "人生而自由，即使生来带着枷锁也是自由的。", "Friedrich Schiller（弗里德里希·席勒）"],
["Was mich nicht umbringt, macht mich stärker.", "凡杀不死我的，必使我更强大。", "Friedrich Nietzsche（弗里德里希·尼采）"],
["Ohne Musik wäre das Leben ein Irrtum.", "没有音乐，生命将是一种错误。", "Friedrich Nietzsche（弗里德里希·尼采）"],
["Hat man sein Warum des Lebens, so verträgt man sich fast mit jedem Wie.", "一个人若知道自己为什么而活，就能忍受几乎任何一种生活。", "Friedrich Nietzsche（弗里德里希·尼采）"],
["In der Rache und in der Liebe ist das Weib barbarischer als der Mann.", "在复仇和爱情中，女人比男人更野蛮。", "Friedrich Nietzsche（弗里德里希·尼采）"],
["Reife des Mannes: das heißt den Ernst wiedergefunden haben, den man als Kind hatte, beim Spiel.", "男人的成熟，就是重新找回儿时游戏时的那份认真。", "Friedrich Nietzsche（弗里德里希·尼采）"],
["Man lügt wohl mit dem Munde, aber mit dem Maule, das man dabei macht, sagt man doch noch die Wahrheit.", "人固然可以用嘴说谎，但说谎时摆出的那副嘴脸，却仍然道出了真相。", "Friedrich Nietzsche（弗里德里希·尼采）"],
["Jedem Anfang wohnt ein Zauber inne.", "每一个开端都自带神奇的魔力。", "Hermann Hesse（赫尔曼·黑塞）"],
["Eile mit Weile.", "欲速则不达。（忙中要从容。）", "Deutsches Sprichwort（德国谚语）"],
["Sinn bekommt das Leben nur durch die Liebe.", "唯有爱，才能赋予生命意义。", "Hermann Hesse (zugeschrieben)（赫尔曼·黑塞（据传））"],
["Wenn wir einen Menschen hassen, hassen wir in seinem Bild etwas, was in uns selber sitzt.", "当我们恨一个人时，我们恨的是他形象中那个存在于我们自己体内的东西。", "Hermann Hesse（赫尔曼·黑塞）"],
["Glück ist Liebe, nichts anderes. Wer lieben kann, ist glücklich.", "幸福就是爱，再无其他。能去爱的人就是幸福的。", "Hermann Hesse (zugeschrieben)（赫尔曼·黑塞（据传））"],
["Es gibt ein Ziel, aber keinen Weg; was wir Weg nennen, ist Zögern.", "有目标，却没有路；我们称之为路的，不过是犹豫。", "Franz Kafka（弗朗茨·卡夫卡）"],
["Da steh ich nun, ich armer Tor! Und bin so klug als wie zuvor.", "如今我站在这里，可怜的傻瓜！却依旧不比从前聪明半分。（自嘲学了半天毫无长进，出自《浮士德》）", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Ohne Hast, aber ohne Rast.", "不慌不忙，亦不休不止。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Die Lüge wird zur Weltordnung gemacht.", "谎言被变成了世界的秩序。", "Franz Kafka（弗朗茨·卡夫卡）"],
["Das Schicksal mischt die Karten, und wir spielen.", "命运负责洗牌，而出牌的是我们自己。", "Arthur Schopenhauer（亚瑟·叔本华）"],
["Meistens belehrt uns erst der Verlust über den Wert der Dinge.", "往往只有在失去之后，我们才懂得事物的价值。", "Arthur Schopenhauer（亚瑟·叔本华）"],
["Jeder Tag ist ein kleines Leben.", "每一天都是一段短暂的生命。", "Arthur Schopenhauer（亚瑟·叔本华）"],
["Wir denken selten an das, was wir haben, aber immer an das, was uns fehlt.", "我们很少想到自己拥有的，却总是惦记着自己欠缺的。", "Arthur Schopenhauer（亚瑟·叔本华）"],
["Natürlicher Verstand kann fast jeden Grad von Bildung ersetzen, aber keine Bildung den natürlichen Verstand.", "天生的心智几乎可以取代任何程度的教育，但教育绝不能取代天生的心智。", "Arthur Schopenhauer（亚瑟·叔本华）"],
["Du musst dein Leben ändern.", "你必须改变你的生活。", "Rainer Maria Rilke（莱纳·玛利亚·里尔克）"],
["Leben Sie jetzt die Fragen.", "请现在就活在这些问题之中。", "Rainer Maria Rilke（莱纳·玛利亚·里尔克）"],
["Ich lebe mein Leben in wachsenden Ringen.", "我在不断扩展的年轮中度过一生。", "Rainer Maria Rilke（莱纳·玛利亚·里尔克）"],
["Also lautet ein Beschluss: Dass der Mensch was lernen muss.", "于是定下一条规矩：人总得学点东西。（出自《马克斯和莫里茨》）", "Wilhelm Busch（威廉·布施）"],
["Irren ist menschlich.", "人非圣贤，孰能无过。（犯错是人之常情。）", "Deutsches Sprichwort（德国谚语）"],
["Das Schönste, was wir erleben können, ist das Geheimnisvolle.", "我们所能经历的最美的事物，便是神秘。", "Albert Einstein（阿尔伯特·爱因斯坦）"],
["Habe Mut, dich deines eigenen Verstandes zu bedienen!", "要有勇气运用你自己的理智！", "Immanuel Kant（伊曼努尔·康德）"],
["Aufklärung ist der Ausgang des Menschen aus seiner selbstverschuldeten Unmündigkeit.", "启蒙就是人类脱离自己所加之于自己的不成熟状态。", "Immanuel Kant（伊曼努尔·康德）"],
["Wenn es einen Glauben gibt, der Berge versetzen kann, so ist es der Glaube an die eigene Kraft.", "如果真有一种能移山的信念，那就是对自身力量的信念。", "Marie von Ebner-Eschenbach（玛丽·冯·埃布纳-埃申巴赫）"],
["Erst kommt das Fressen, dann kommt die Moral.", "先要吃饱肚子，然后才能谈道德。", "Bertolt Brecht（贝托尔特·布莱希特）"],
["Ändere die Welt, sie braucht es.", "去改变世界吧，它需要改变。", "Bertolt Brecht（贝托尔特·布莱希特）"],
["Wer nicht wagt, der nicht gewinnt.", "不入虎穴，焉得虎子。（不冒险者无所获。）", "Deutsches Sprichwort（德国谚语）"],
["Leben und leben lassen.", "宽容待人。（自己生活，也让别人生活。）", "Deutsches Sprichwort（德国谚语）"],
["Müßiggang ist aller Laster Anfang.", "无所事事是万恶之源。", "Deutsches Sprichwort（德国谚语）"],
["Für das Können gibt es nur einen Beweis: das Tun.", "证明能力的唯一标准：行动。", "Marie von Ebner-Eschenbach（玛丽·冯·埃布纳-埃申巴赫）"],
["Vertrauen ist Mut, und Treue ist Kraft.", "信任是勇气，而忠诚是力量。", "Marie von Ebner-Eschenbach（玛丽·冯·埃布纳-埃申巴赫）"],
["Beim Menschen ist es wie beim Velo. Nur wenn er fährt, kann er bequem die Balance halten.", "人就像自行车，只有骑起来，才能轻松地保持平衡。（Velo 是瑞士德语的“自行车”）", "Albert Einstein（阿尔伯特·爱因斯坦）"],
["Die glücklichen Sklaven sind die erbittertsten Feinde der Freiheit.", "感到幸福的奴隶，是自由最死硬的敌人。", "Marie von Ebner-Eschenbach（玛丽·冯·埃布纳-埃申巴赫）"],
["Liebe geht durch den Magen.", "要想抓住一个人的心，先要抓住他的胃。（爱要穿过胃。）", "Deutsches Sprichwort（德国谚语）"],
["Vater werden ist nicht schwer, Vater sein dagegen sehr.", "当上父亲不难，做好父亲却很难。", "Wilhelm Busch（威廉·布施）"],
["Denk ich an Deutschland in der Nacht, dann bin ich um den Schlaf gebracht.", "夜半思及德意志，我便再难入眠。", "Heinrich Heine（海因里希·海涅）"],
["Die Zensur ist die jüngere von zwei schändlichen Schwestern, die ältere heißt Inquisition.", "审查制度是两个无耻姐妹中的妹妹，姐姐名叫宗教裁判所。", "Johann Nepomuk Nestroy（约翰·内波穆克·内斯特罗伊）"],
["Am Mut hängt der Erfolg.", "成功往往取决于勇气。", "Theodor Fontane (zugeschrieben)（台奥多尔·冯塔纳（据传））"],
["Wie man in den Wald hineinruft, so schallt es heraus.", "你怎样待人，人就怎样待你。（你怎么对着森林喊，森林就怎么回应你。）", "Deutsches Sprichwort（德国谚语）"],
["Ordnung ist das halbe Leben.", "秩序是生活的一半。", "Deutsches Sprichwort（德国谚语）"],
["Wenn man glücklich ist, soll man nicht noch glücklicher sein wollen.", "当你已经幸福时，就不要再妄求更幸福。", "Theodor Fontane (zugeschrieben)（台奥多尔·冯塔纳（据传））"],
["Stets findet Überraschung statt. Da, wo man's nicht erwartet hat.", "意外总会发生，偏偏在你没料到的地方。", "Wilhelm Busch（威廉·布施）"],
["Wer durch des Argwohns Brille schaut, sieht Raupen selbst im Sauerkraut.", "戴着猜疑眼镜看东西的人，连酸菜里都能看出毛毛虫。", "Wilhelm Busch（威廉·布施）"],
["Man bleibt jung, solange man noch lernen, neue Gewohnheiten annehmen und Widerspruch ertragen kann.", "只要还能学习、接受新习惯、容得下反对意见，人就依然年轻。", "Marie von Ebner-Eschenbach（玛丽·冯·埃布纳-埃申巴赫）"],
["Meistens hat, wenn zwei sich scheiden, einer etwas mehr zu leiden.", "两人分道扬镳时，通常总有一方要多受些苦。", "Wilhelm Busch（威廉·布施）"],
["Ein einziger dankbarer Gedanke gen Himmel ist das vollkommenste Gebet.", "一个感恩苍天的心念，便是最完美的祈祷。", "Gotthold Ephraim Lessing（戈特霍尔德·埃弗拉伊姆·莱辛）"],
["Aus nichts wird nichts.", "无中不能生有。", "Deutsches Sprichwort（德国谚语）"],
["Geduld ist ein bitteres Kraut, aber es trägt süße Früchte.", "忍耐是苦涩的草，但结出甜美的果实。", "Deutsches Sprichwort（德国谚语）"],
["Der Vorteil der Klugheit besteht darin, dass man sich dumm stellen kann. Das Gegenteil ist schon schwieriger.", "聪明的优势在于可以装傻，反过来可就难多了。", "Kurt Tucholsky（库尔特·图霍尔斯基）"],
["Erst die Arbeit, dann das Vergnügen.", "先苦后甜。（先工作，后娱乐。）", "Deutsches Sprichwort（德国谚语）"],
["Den Freund erkennt man in der Not.", "患难见真情。（困境中方知谁是真友。）", "Deutsches Sprichwort（德国谚语）"],
["Nichts ist schwerer und nichts erfordert mehr Charakter, als sich im offenen Gegensatz zu seiner Zeit zu befinden.", "没有什么比公开站到自己时代的对立面更考验品格的了。", "Kurt Tucholsky（库尔特·图霍尔斯基）"],
["An allem Unfug, der passiert, sind nicht etwa nur die schuld, die ihn tun, sondern auch die, die ihn nicht verhindern.", "一切正在发生的荒唐事，责任不仅在于作恶者，也在于不加阻止者。", "Erich Kästner（埃里希·凯斯特纳）"],
["Eins, zwei, drei! Im Sauseschritt läuft die Zeit; wir laufen mit.", "一、二、三！时间飞奔向前，我们也跟着奔跑。", "Wilhelm Busch（威廉·布施）"],
["Ein fauler Apfel steckt hundert gesunde an.", "一颗烂苹果，坏了一筐好苹果。", "Deutsches Sprichwort（德国谚语）"],
["Wird's besser? Wird's schlimmer? fragt man alljährlich. Seien wir ehrlich: Leben ist immer lebensgefährlich.", "人们年复一年地问着：会变好吗？会变坏吗？坦白说吧：活着总有生命危险。", "Erich Kästner（埃里希·凯斯特纳）"],
["Bäume wachsen nicht in den Himmel.", "树长得再高也碰不到天。（事物总有其限度。）", "Deutsches Sprichwort（德国谚语）"],
["Die Geschichte aller bisherigen Gesellschaft ist die Geschichte von Klassenkämpfen.", "至今一切社会的历史都是阶级斗争的历史。", "Karl Marx / Friedrich Engels（卡尔·马克思 / 弗里德里希·恩格斯）"],
["Proletarier aller Länder, vereinigt euch!", "全世界无产者，联合起来！", "Karl Marx / Friedrich Engels（卡尔·马克思 / 弗里德里希·恩格斯）"],
["Ein Abschied schmerzt immer, auch wenn man sich schon lange darauf gefreut hat.", "告别总是令人痛苦的，即使你早就盼着它。", "Arthur Schnitzler（阿图尔·施尼茨勒）"],
["Bereit sein ist viel, warten können ist mehr, doch erst: den rechten Augenblick nützen ist alles.", "准备好固然重要，能耐心等待更难得，但最关键的还是：抓住时机。", "Arthur Schnitzler（阿图尔·施尼茨勒）"],
["Wo Kinder sind, da ist ein goldenes Zeitalter.", "哪里有孩子，哪里就是黄金时代。", "Novalis（诺瓦利斯）"],
["Jeder geliebte Gegenstand ist der Mittelpunkt eines Paradieses.", "每一样被爱着的事物，都是一座天堂的中心。", "Novalis（诺瓦利斯）"],
["Die Grenzen meiner Sprache bedeuten die Grenzen meiner Welt.", "我语言的界限，意味着我世界的界限。", "Ludwig Wittgenstein（路德维希·维特根斯坦）"],
["Der Tod ist kein Ereignis des Lebens. Den Tod erlebt man nicht.", "死亡不是生命中的事件。人是体验不到死亡的。", "Ludwig Wittgenstein（路德维希·维特根斯坦）"],
["Wo Es war, soll Ich werden.", "本我所在之处，自我应当取而代之。", "Sigmund Freud（西格蒙德·弗洛伊德）"],
["Ein blindes Huhn findet auch mal ein Korn.", "瞎猫碰上死耗子。（瞎眼的母鸡也能找到谷粒。）", "Deutsches Sprichwort（德国谚语）"],
["Der Apfel fällt nicht weit vom Stamm.", "有其父必有其子。（苹果落地不会离树干太远。）", "Deutsches Sprichwort（德国谚语）"],
["Hunde, die bellen, beißen nicht.", "吠犬不咬人。", "Deutsches Sprichwort（德国谚语）"],
["Pech im Spiel, Glück in der Liebe.", "赌场失意，情场得意。", "Deutsches Sprichwort（德国谚语）"],
["Wer A sagt, muss auch B sagen.", "既然开了头，就得做到底。（说了A，就得说B。）", "Deutsches Sprichwort（德国谚语）"],
["Wer im Glashaus sitzt, sollte nicht mit Steinen werfen.", "自身不净者，勿揭他人短。（坐在玻璃房里的人，不该扔石头。）", "Deutsches Sprichwort（德国谚语）"],
["Kommt Zeit, kommt Rat.", "车到山前必有路。（时间一到，办法自来。）", "Deutsches Sprichwort（德国谚语）"],
["Schuster, bleib bei deinem Leisten.", "守好本分，莫论外行。（鞋匠，请守着你的鞋楦。）", "Deutsches Sprichwort（德国谚语）"],
["Man sieht sich immer zweimal im Leben.", "人生何处不相逢。", "Deutsches Sprichwort（德国谚语）"],
["Besser ein Spatz in der Hand als eine Taube auf dem Dach.", "双鸟在林不如一鸟在手。（手中的麻雀胜过屋顶的鸽子。）", "Deutsches Sprichwort（德国谚语）"],
["Lehrjahre sind keine Herrenjahre.", "学徒期不是做老爷的日子。（学艺必受苦。）", "Deutsches Sprichwort（德国谚语）"],
["Es ist noch kein Meister vom Himmel gefallen.", "没有人天生就是大师。", "Deutsches Sprichwort（德国谚语）"],
["Wer sein eigenes Leben und das seiner Mitmenschen als sinnlos empfindet, der ist nicht nur unglücklich, sondern auch kaum lebensfähig.", "觉得自己的生命和同类的生命毫无意义的人，不仅不幸，而且几乎无法生存。", "Albert Einstein（阿尔伯特·爱因斯坦）"],
["Alles Große in unserer Welt geschieht nur, weil jemand mehr tut, als er muss.", "世间所有的伟大之所以发生，只因有人做了超出职责之外的事。", "Hermann Gmeiner（赫尔曼·格迈纳）"],
["Dieses war der erste Streich, doch der zweite folgt sogleich.", "这是第一个恶作剧，第二个马上就来。（出自《马克斯和莫里茨》）", "Wilhelm Busch（威廉·布施）"],
["Aller guten Dinge sind drei.", "好事成三。", "Deutsches Sprichwort（德国谚语）"],
["Arbeit bringt Brot, Faulenzen Hungersnot.", "劳动带来面包，懒惰带来饥荒。", "Deutsches Sprichwort（德国谚语）"],
["Selbsterkenntnis ist der erste Schritt zur Besserung.", "有自知之明是改正错误的第一步。", "Deutsches Sprichwort（德国谚语）"],
["Ein voller Bauch studiert nicht gern.", "饱汉不爱读书。（肚子饱了不想学习。）", "Deutsches Sprichwort（德国谚语）"],
["Man muss etwas Neues machen, um etwas Neues zu sehen.", "要做新的事，才能看见新的东西。", "Georg Christoph Lichtenberg（格奥尔格·克里斯托弗·利希滕贝格）"],
["Jeder Mensch ist ein Künstler.", "每个人都是艺术家。", "Joseph Beuys（约瑟夫·博伊斯）"],
["Es wächst der Mensch mit seinen größern Zwecken.", "人随着更远大的目标而成长。", "Friedrich Schiller（弗里德里希·席勒）"],
["Die Hoffnung stirbt zuletzt.", "希望是最后才消亡的。", "Deutsches Sprichwort（德国谚语）"],
["Alter schützt vor Torheit nicht.", "岁数大，不一定不犯傻。", "Deutsches Sprichwort（德国谚语）"],
["Man muss den Dingen die eigene, stille ungestörte Entwicklung lassen.", "应当让事物按自己的方式，安静而不受打扰地成长。", "Rainer Maria Rilke（莱纳·玛利亚·里尔克）"],
["Es ist nichts schrecklicher als eine tätige Unwissenheit.", "没有什么比积极行动的盲目无知更可怕的了。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Es gibt keinen Zufall.", "世间没有偶然。", "Friedrich Schiller（弗里德里希·席勒）"],
["Nichts wird so oft unwiederbringlich versäumt wie eine Gelegenheit, die sich täglich bietet.", "最常被错过且一去不返的，恰恰是每天都摆在眼前的机会。", "Marie von Ebner-Eschenbach（玛丽·冯·埃布纳-埃申巴赫）"],
["Aufgeschoben ist nicht aufgehoben.", "延缓不等于取消。", "Deutsches Sprichwort（德国谚语）"],
["Phantasie haben heißt nicht, sich etwas auszudenken, es heißt, sich aus den Dingen etwas zu machen.", "拥有想象力，不是凭空臆想，而是从事物中造出些什么。", "Thomas Mann (zugeschrieben)（托马斯·曼（据传））"],
["Humor ist der Knopf, der verhindert, dass uns der Kragen platzt.", "幽默是一颗纽扣，能防止我们的衣领崩开。（jemandem platzt der Kragen 意为“某人气炸了”，一语双关）", "Joachim Ringelnatz (zugeschrieben)（约阿希姆·林格尔纳茨（据传））"],
["Man muss das Wahre immer wiederholen.", "真理必须被不断地重申。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Einbildung ist auch eine Bildung.", "自负也算一种“学问”。（Einbildung 意为自负，Bildung 意为学识，一语双关）", "Deutsches Sprichwort（德国谚语）"],
["In der Kunst ist das Beste gut genug.", "在艺术中，唯有最好的才够好。（出自《意大利游记》）", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["In der Kürze liegt die Würze.", "简短才是精华。", "Deutsches Sprichwort（德国谚语）"],
["Ein Mann, ein Wort.", "君子一言，驷马难追。", "Deutsches Sprichwort（德国谚语）"],
["Was Hänschen nicht lernt, lernt Hans nimmermehr.", "幼时不学，长大难学。（小汉斯没学会的，大汉斯永远学不会。）", "Deutsches Sprichwort（德国谚语）"],
["Wenn zwei sich streiten, freut sich der Dritte.", "鹬蚌相争，渔翁得利。", "Deutsches Sprichwort（德国谚语）"],
["Wer nicht hören will, muss fühlen.", "不听劝告者必尝苦果。", "Deutsches Sprichwort（德国谚语）"],
["Keine Antwort ist auch eine Antwort.", "不回答本身也是一种回答。", "Deutsches Sprichwort（德国谚语）"],
["Aus Schaden wird man klug.", "吃一堑，长一智。", "Deutsches Sprichwort（德国谚语）"],
["Not macht erfinderisch.", "需要是发明之母。（困境让人富有创造力。）", "Deutsches Sprichwort（德国谚语）"],
["Man soll den Tag nicht vor dem Abend loben.", "不到傍晚，别夸这一天。（事情没到最后，别高兴太早。）", "Deutsches Sprichwort（德国谚语）"],
["Andere Länder, andere Sitten.", "十里不同风，百里不同俗。", "Deutsches Sprichwort（德国谚语）"],
["Eine Schwalbe macht noch keinen Sommer.", "孤燕不成夏。", "Deutsches Sprichwort（德国谚语）"],
["Wer sich zum Wurm macht, kann nachher nicht klagen, wenn er mit Füßen getreten wird.", "把自己变成虫子的人，就不要抱怨被人踩在脚下。", "Immanuel Kant（伊曼努尔·康德）"],
["Gelegenheit macht Diebe.", "见机起盗心。", "Deutsches Sprichwort（德国谚语）"],
["Nicht da ist man daheim, wo man seinen Wohnsitz hat, sondern wo man verstanden wird.", "家不在你居住的地方，而在你被理解的地方。", "Christian Morgenstern（克里斯蒂安·摩根施特恩）"],
["Die Welt ist klein.", "世界真小。", "Deutsches Sprichwort（德国谚语）"],
["Lachen ist gesund.", "笑有益健康。（笑一笑，十年少。）", "Deutsches Sprichwort（德国谚语）"],
["Was du ererbt von deinen Vätern hast, erwirb es, um es zu besitzen.", "你从父辈那里继承的东西，要靠自己努力去赢得，才能真正拥有。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Vorfreude ist die schönste Freude.", "期待本身就是最美的喜悦。", "Deutsches Sprichwort（德国谚语）"],
["Träume sind Schäume.", "梦如泡影。", "Deutsches Sprichwort（德国谚语）"],
["Wer zuerst kommt, mahlt zuerst.", "捷足先登。（先到先磨面。）", "Deutsches Sprichwort（德国谚语）"],
["Arbeit schändet nicht.", "劳动不丢人。", "Deutsches Sprichwort（德国谚语）"],
["Blut ist dicker als Wasser.", "血浓于水。", "Deutsches Sprichwort（德国谚语）"],
["Die Zeit heilt alle Wunden.", "时间能治愈一切创伤。", "Deutsches Sprichwort（德国谚语）"],
["Kleinvieh macht auch Mist.", "积少成多。（小牲口也能产肥料。）", "Deutsches Sprichwort（德国谚语）"],
["Ein Tropfen auf den heißen Stein.", "杯水车薪。（热石头上的一滴水。）", "Deutsches Sprichwort（德国谚语）"],
["Was sich liebt, das neckt sich.", "打是亲，骂是爱。", "Deutsches Sprichwort（德国谚语）"],
["Einem geschenkten Gaul schaut man nicht ins Maul.", "馈赠之物，勿吹毛求疵。", "Deutsches Sprichwort（德国谚语）"],
["In der Not frisst der Teufel Fliegen.", "饥不择食。", "Deutsches Sprichwort（德国谚语）"],
["Jeder ist sich selbst der Nächste.", "每个人都先顾着自己。", "Deutsches Sprichwort（德国谚语）"],
["Was du heute kannst besorgen, das verschiebe nicht auf morgen.", "今日事，今日毕。", "Deutsches Sprichwort（德国谚语）"],
["Wo Rauch ist, ist auch Feuer.", "无风不起浪。", "Deutsches Sprichwort（德国谚语）"],
["Kinder und Narren sagen die Wahrheit.", "孩子和傻子说真话。（童言无欺。）", "Deutsches Sprichwort（德国谚语）"],
["Liebe macht blind.", "爱情令人盲目。", "Deutsches Sprichwort（德国谚语）"],
["Keine Rosen ohne Dornen.", "玫瑰皆有刺。", "Deutsches Sprichwort（德国谚语）"],
["Wer anderen eine Grube gräbt, fällt selbst hinein.", "害人终害己。", "Deutsches Sprichwort（德国谚语）"],
["Kleider machen Leute.", "人靠衣装，马靠鞍。（衣服造就人。）", "Deutsches Sprichwort（德国谚语）"],
["Des einen Freud ist des anderen Leid.", "几家欢喜几家愁。", "Deutsches Sprichwort（德国谚语）"],
["Scherben bringen Glück.", "碎碎平安。", "Deutsches Sprichwort（德国谚语）"],
["Papier ist geduldig.", "白纸黑字不等于事实。（纸是极有耐心的。）", "Deutsches Sprichwort（德国谚语）"],
["Das letzte Hemd hat keine Taschen.", "生不带来，死不带去。", "Deutsches Sprichwort（德国谚语）"],
["Vorsicht ist die Mutter der Porzellankiste.", "小心驶得万年船。", "Deutsches Sprichwort（德国谚语）"],
["Edel sei der Mensch, hilfreich und gut!", "人应当高尚、乐于助人且善良！", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Die Tat ist alles, nichts der Ruhm.", "行动就是一切，虚名毫无意义。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Weil, so schließt er messerscharf, nicht sein kann, was nicht sein darf.", "因为——他推论得斩钉截铁——不该存在的事，就不可能存在。", "Christian Morgenstern（克里斯蒂安·摩根施特恩）"],
["In der Beschränkung zeigt sich erst der Meister.", "在限制之中，方显大师本色。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Überhaupt lernt man nur von dem, den man liebt.", "总的来说，人只能向自己所爱的人学习。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Die ich rief, die Geister, werd ich nun nicht los.", "我召来的那些精灵，如今却再也摆脱不掉了。（出自《魔法师的学徒》，比喻惹出的麻烦收不了场）", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Lieber ein Ende mit Schrecken als ein Schrecken ohne Ende.", "宁可痛苦地结束，也不要无尽的痛苦。", "Ferdinand von Schill（费迪南·冯·席尔）"],
["Ich bin der Geist, der stets verneint.", "我是那始终否定的精神。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Blut ist ein ganz besondrer Saft.", "血是一种非常特别的汁液。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Name ist Schall und Rauch.", "名字不过是虚无的声响和青烟。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Es ist nicht genug zu wollen, man muss auch tun.", "光有愿望是不够的，还必须付诸行动。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Schlafende Hunde soll man nicht wecken.", "别自找麻烦。（别唤醒沉睡的狗。）", "Deutsches Sprichwort（德国谚语）"],
["Reisende soll man nicht aufhalten.", "不应阻拦要离去的人。", "Deutsches Sprichwort（德国谚语）"],
["Das Leben gehört den Lebendigen an, und wer lebt, muss auf Wechsel gefasst sein.", "生活属于活着的人，活着就必须时刻准备迎接改变。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Es ist des Lernens kein Ende.", "学无止境。", "Robert Schumann（罗伯特·舒曼）"],
["Lernst du nicht fremde Sprachen in den Ländern am besten, wo sie zu Hause sind?", "学外语，难道不是在它的家乡学得最好吗？（出自《威廉·迈斯特的漫游时代》）", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Ich habe keine besondere Begabung, sondern bin nur leidenschaftlich neugierig.", "我没有特殊天赋，我只是拥有充满激情的求知欲。", "Albert Einstein（阿尔伯特·爱因斯坦）"],
["Das ewig Unbegreifliche an der Welt ist ihre Begreiflichkeit.", "世界最不可思议之处，在于它是可以被理解的。", "Albert Einstein（阿尔伯特·爱因斯坦）"],
["Wer einmal lügt, dem glaubt man nicht, und wenn er auch die Wahrheit spricht.", "骗人一次，哪怕说真话也没人信。", "Deutsches Sprichwort（德国谚语）"],
["Zwei Dumme, ein Gedanke.", "两个笨蛋，同一个想法。（自嘲式的“英雄所见略同”）", "Deutsches Sprichwort（德国谚语）"],
["Gegensätze ziehen sich an.", "性格互补者相互吸引。（对立面相互吸引。）", "Deutsches Sprichwort（德国谚语）"],
["Müde macht uns die Arbeit, die wir liegenlassen, nicht die, die wir tun.", "让我们疲惫的，不是正在做的工作，而是搁置未做的工作。", "Marie von Ebner-Eschenbach（玛丽·冯·埃布纳-埃申巴赫）"],
["Irrtümer haben ihren Wert; jedoch nur hie und da. Nicht jeder, der nach Indien fährt, entdeckt Amerika.", "错误自有其价值，但只是偶尔。并非每个驶向印度的人，都能发现美洲。", "Erich Kästner（埃里希·凯斯特纳）"],
["Nicht was wir erleben, sondern wie wir empfinden, was wir erleben, macht unser Schicksal aus.", "构成我们命运的，并非我们经历了什么，而是我们如何去感受这些经历。", "Marie von Ebner-Eschenbach（玛丽·冯·埃布纳-埃申巴赫）"],
["Was lange währt, wird endlich gut.", "功到自然成。（历时久远的事，最终总会变好。）", "Deutsches Sprichwort（德国谚语）"],
["Der Mensch ist etwas, das überwunden werden soll.", "人是一种应当被超越的东西。", "Friedrich Nietzsche（弗里德里希·尼采）"],
["Gelobt sei, was hart macht.", "使人坚强的，当受赞美。", "Friedrich Nietzsche（弗里德里希·尼采）"],
["Alle verschwiegenen Wahrheiten werden giftig.", "所有被隐瞒的真理都会变得有毒。", "Friedrich Nietzsche（弗里德里希·尼采）"],
["Nicht durch Zorn, sondern durch Lachen tötet man.", "人不是用愤怒来杀戮，而是用笑声。", "Friedrich Nietzsche（弗里德里希·尼采）"],
["Man vergilt einem Lehrer schlecht, wenn man immer nur der Schüler bleibt.", "如果永远只做学生，那便是对老师的糟糕回报。", "Friedrich Nietzsche（弗里德里希·尼采）"],
["Ich bin kein Mensch, ich bin Dynamit.", "我不是人，我是炸药。", "Friedrich Nietzsche（弗里德里希·尼采）"],
["Glück ist das Gefühl davon, dass die Macht wächst.", "幸福，就是感到权力在增长。", "Friedrich Nietzsche（弗里德里希·尼采）"],
["Mancher findet sein Herz nicht eher, als bis er seinen Kopf verliert.", "有些人直到失去理智，才找到自己的心。", "Friedrich Nietzsche（弗里德里希·尼采）"],
["Man brauche gewöhnliche Worte und sage ungewöhnliche Dinge.", "用平常的词语，说不平常的事。", "Arthur Schopenhauer（亚瑟·叔本华）"],
["Die Freunde nennen sich aufrichtig, die Feinde sind es.", "朋友自称真诚，而敌人才是真的真诚。", "Arthur Schopenhauer（亚瑟·叔本华）"],
["Wer nicht die Einsamkeit liebt, der liebt auch nicht die Freiheit.", "不热爱孤独的人，也不热爱自由。", "Arthur Schopenhauer（亚瑟·叔本华）"],
["Man muss die Feste feiern, wie sie fallen.", "逢节就过，及时行乐。（节日怎么降临，就怎么庆祝。）", "Deutsches Sprichwort（德国谚语）"],
["Bescheidenheit bei mittelmäßigen Fähigkeiten ist bloße Ehrlichkeit.", "对于平庸之才而言，谦虚只不过是诚实而已。", "Arthur Schopenhauer（亚瑟·叔本华）"],
["Lesen heißt mit einem fremden Kopfe, statt des eigenen, denken.", "阅读就是用别人的头脑，而不是自己的头脑去思考。", "Arthur Schopenhauer（亚瑟·叔本华）"],
["Raum ist in der kleinsten Hütte.", "再小的茅屋也有容身之地。（原诗下句：für ein glücklich liebend Paar，即“容得下一对幸福相爱的恋人”）", "Friedrich Schiller（弗里德里希·席勒）"],
["Mit der Dummheit kämpfen Götter selbst vergebens.", "面对愚蠢，连众神也是无能为力。", "Friedrich Schiller（弗里德里希·席勒）"],
["Gefährlich ist's, den Leu zu wecken.", "唤醒雄狮是危险的。", "Friedrich Schiller（弗里德里希·席勒）"],
["Verbunden werden auch die Schwachen mächtig.", "只要团结一致，弱者也能变得强大。", "Friedrich Schiller（弗里德里希·席勒）"],
["Das Alte stürzt, es ändert sich die Zeit.", "旧事物在崩塌，时代正在改变。", "Friedrich Schiller（弗里德里希·席勒）"],
["Früh übt sich, was ein Meister werden will.", "想要成为大师，必须早早开始磨炼。", "Friedrich Schiller（弗里德里希·席勒）"],
["Der Starke ist am mächtigsten allein.", "强者独处时最为强大。", "Friedrich Schiller（弗里德里希·席勒）"],
["Am Ziel deiner Wünsche wirst du jedenfalls eines vermissen: dein Wandern zum Ziel.", "到达心愿的终点时，你总会怀念一样东西：你走向目标的那段路。", "Marie von Ebner-Eschenbach（玛丽·冯·埃布纳-埃申巴赫）"],
["Man muss seinen Feinden verzeihen, aber nicht früher, als bis sie gehenkt werden.", "我们应当宽恕敌人，但必须等到他们被绞死之后。", "Heinrich Heine（海因里希·海涅）"],
["Alles Gescheite ist schon gedacht worden, man muss nur versuchen, es noch einmal zu denken.", "一切聪明的想法早已有人想过，我们只需尝试把它再想一遍。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Philosophie ist eigentlich Heimweh.", "哲学，其实就是一种思乡病。", "Novalis（诺瓦利斯）"],
["Die Poesie ist das echt absolut Reelle.", "诗才是真正绝对的真实。", "Novalis（诺瓦利斯）"],
["Ein Charakter ist ein vollständig gebildeter Wille.", "品格就是彻底成熟并定型的意志。", "Novalis（诺瓦利斯）"],
["Man sieht oft etwas hundertmal, tausendmal, ehe man es zum allerersten Mal wirklich sieht.", "一样东西，我们往往看过上百遍、上千遍，才第一次真正看见它。", "Christian Morgenstern（克里斯蒂安·摩根施特恩）"],
["Das ist ein weites Feld.", "那可是一个广阔的领域啊（意指：这话说来可就长了）。", "Theodor Fontane（台奥多尔·冯塔纳）"],
["Der Schoß ist fruchtbar noch, aus dem das kroch.", "孕育出这怪物的温床，如今依然肥沃。", "Bertolt Brecht（贝托尔特·布莱希特）"],
["Das Denken gehört zu den größten Vergnügungen der menschlichen Rasse.", "思考，是人类最大的乐趣之一。", "Bertolt Brecht（贝托尔特·布莱希特）"],
["Unglücklich das Land, das Helden nötig hat.", "不幸的是那个需要英雄的国度。", "Bertolt Brecht（贝托尔特·布莱希特）"],
["Harte Schale, weicher Kern.", "外刚内柔。（硬壳软核。）", "Deutsches Sprichwort（德国谚语）"],
["Ein Käfig ging einen Vogel suchen.", "一只笼子去寻找一只鸟。", "Franz Kafka（弗朗茨·卡夫卡）"],
["Die Gedanken sind frei.", "思想是自由的。", "Deutsches Volkslied（德国民歌）"],
["Oh, Hoffnung genug, unendlich viel Hoffnung – nur nicht für uns.", "哦，希望多的是，无穷无尽的希望——只是不属于我们。", "Franz Kafka (nach Max Brod)（弗朗茨·卡夫卡（据马克斯·布罗德转述））"],
["Man hat nur Angst, wenn man mit sich selber nicht einig ist.", "人只有在与自己不和时，才会感到恐惧。", "Hermann Hesse（赫尔曼·黑塞）"],
["Die Praxis sollte das Ergebnis des Nachdenkens sein, nicht umgekehrt.", "实践应当是深思熟虑的结果，而不是反过来。", "Hermann Hesse (zugeschrieben)（赫尔曼·黑塞（据传））"],
["Damit das Mögliche entsteht, muss immer wieder das Unmögliche versucht werden.", "为了让可能的事物诞生，必须不断地去尝试不可能之事。", "Hermann Hesse（赫尔曼·黑塞）"],
["Ein guter Anfang ist die halbe Arbeit.", "良好的开端是成功的一半。", "Deutsches Sprichwort（德国谚语）"],
["Das Volk versteht das meiste falsch; aber es fühlt das meiste richtig.", "民众对大多数事情的理解往往是错的；但他们的直觉感受却往往是对的。", "Kurt Tucholsky（库尔特·图霍尔斯基）"],
["Die beste Bildung findet ein gescheiter Mensch auf Reisen.", "聪明人能在旅行中获得最好的教育。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Die Basis einer jeden gesunden Ordnung ist ein großer Papierkorb.", "任何健康秩序的基础，都是一个巨大的废纸篓。", "Kurt Tucholsky（库尔特·图霍尔斯基）"],
["Handle nur nach derjenigen Maxime, durch die du zugleich wollen kannst, dass sie ein allgemeines Gesetz werde.", "只按照你同时也愿意它成为普遍法则的那个准则去行动。", "Immanuel Kant（伊曼努尔·康德）"],
["Wie man sich bettet, so liegt man.", "自作自受。（你怎么铺床，就怎么躺着。）", "Deutsches Sprichwort（德国谚语）"],
["Zweifle an allem wenigstens einmal, und wäre es auch der Satz: zweimal zwei ist vier.", "至少对一切事物怀疑一次，哪怕是“二乘二等于四”这样的常理。", "Georg Christoph Lichtenberg（格奥尔格·克里斯托弗·利希滕贝格）"],
["Wer nichts als Chemie versteht, versteht auch die nicht recht.", "只懂化学的人，其实连化学也并没有真正懂。", "Georg Christoph Lichtenberg（格奥尔格·克里斯托弗·利希滕贝格）"],
["Ich kann freilich nicht sagen, ob es besser werden wird, wenn es anders wird; aber so viel kann ich sagen: es muss anders werden, wenn es gut werden soll.", "我确实无法保证改变后一定会更好；但我敢说，若想变好，就必须改变。", "Georg Christoph Lichtenberg（格奥尔格·克里斯托弗·利希滕贝格）"],
["Ein Buch ist ein Spiegel, wenn ein Affe hineinsieht, so kann kein Apostel herausgucken.", "书是一面镜子，如果一只猴子往里看，里面绝不会照出一个使徒来。", "Georg Christoph Lichtenberg（格奥尔格·克里斯托弗·利希滕贝格）"],
["Ein Aphorismus braucht nicht wahr zu sein, aber er soll die Wahrheit überflügeln.", "一句格言不必真实，但它应当比真实飞得更高。", "Karl Kraus（卡尔·克劳斯）"],
["Das Geheimnis des Agitators ist, sich so dumm zu machen, wie seine Zuhörer sind, damit sie glauben, sie seien so gescheit wie er.", "煽动者的秘诀就是把自己降到和听众一样蠢，这样听众就会觉得自己和他一样聪明。", "Karl Kraus（卡尔·克劳斯）"],
["Sprache ist die Mutter, nicht die Magd des Gedankens.", "语言是思想的母亲，而非思想的侍女。", "Karl Kraus（卡尔·克劳斯）"],
["Der Langsamste, der sein Ziel nicht aus den Augen verliert, geht noch immer geschwinder als jener, der ohne Ziel umherirrt.", "最慢的人只要不丢掉目标，也总比漫无目的四处乱转的人走得快。", "Gotthold Ephraim Lessing（戈特霍尔德·埃弗拉伊姆·莱辛）"],
["Nur wer erwachsen wird und ein Kind bleibt, ist ein Mensch.", "唯有长大成人却依然保有一颗童心的人，才算真正的人。", "Erich Kästner（埃里希·凯斯特纳）"],
["Was auch immer geschieht, nie dürft ihr so tief sinken, von dem Kakao, durch den man euch zieht, auch noch zu trinken.", "无论发生什么，你们都不能堕落到这种地步：被人拖进可可里嘲弄，还把那可可喝下去。（durch den Kakao ziehen 意为嘲弄某人，一语双关）", "Erich Kästner（埃里希·凯斯特纳）"],
["Die Weltgeschichte ist das Weltgericht.", "世界历史就是对世界的最终审判。", "Friedrich Schiller（弗里德里希·席勒）"],
["Was der Bauer nicht kennt, das frisst er nicht.", "农民没见过的东西，他是绝对不吃的（形容墨守成规、拒绝新事物）。", "Deutsches Sprichwort（德国谚语）"],
["In der Ruhe liegt die Kraft.", "力量源自内心的平静。", "Deutsches Sprichwort（德国谚语）"],
["Hochmut kommt vor dem Fall.", "骄者必败。", "Deutsches Sprichwort（德国谚语）"],
["Die Katze lässt das Mausen nicht.", "江山易改，本性难移。（猫改不了抓老鼠。）", "Deutsches Sprichwort（德国谚语）"],
["Gut Ding will Weile haben.", "慢工出细活。", "Deutsches Sprichwort（德国谚语）"],
["Jedem Tierchen sein Pläsierchen.", "萝卜青菜，各有所爱。（每只小动物都有自己的小乐趣。）", "Deutsches Sprichwort（德国谚语）"],
["Man sieht den Wald vor lauter Bäumen nicht.", "只见树木，不见森林。", "Deutsches Sprichwort（德国谚语）"],
["Geld regiert die Welt.", "有钱能使鬼推磨。（金钱统治世界。）", "Deutsches Sprichwort（德国谚语）"],
["Alte Liebe rostet nicht.", "旧情难忘。（古老的爱情不会生锈。）", "Deutsches Sprichwort（德国谚语）"],
["Ein gebranntes Kind scheut das Feuer.", "一朝被蛇咬，十年怕井绳。（被烧过的孩子怕火。）", "Deutsches Sprichwort（德国谚语）"],
["Viele Köche verderben den Brei.", "厨子多了煮坏粥（形容人多嘴杂办不成事）。", "Deutsches Sprichwort（德国谚语）"],
["Übermut tut selten gut.", "得意忘形，少有好下场。", "Deutsches Sprichwort（德国谚语）"],
["Auf Regen folgt Sonnenschein.", "雨过天晴。", "Deutsches Sprichwort（德国谚语）"],
["Ernst ist das Leben, heiter ist die Kunst.", "严肃的是人生，欢快的是艺术。", "Friedrich Schiller（弗里德里希·席勒）"],
["Jeder kehre vor seiner eigenen Tür.", "各人先扫自家门前。（先管好自己，再去说别人。）", "Deutsches Sprichwort（德国谚语）"],
["Gegen eine Dummheit, die gerade in Mode ist, kommt keine Klugheit auf.", "面对正流行的愚蠢，任何聪明才智都无济于事。", "Theodor Fontane（台奥多尔·冯塔纳）"],
["Wer nichts weiß, muss alles glauben.", "什么都不知道的人，只能什么都相信。", "Marie von Ebner-Eschenbach（玛丽·冯·埃布纳-埃申巴赫）"],
["Es gibt nichts Gutes, außer man tut es.", "除非付诸行动，否则就谈不上善。", "Erich Kästner（埃里希·凯斯特纳）"],
["Wo aber Gefahr ist, wächst das Rettende auch.", "哪里有危险，哪里就生出拯救的力量。", "Friedrich Hölderlin（弗里德里希·荷尔德林）"],
["Die Axt im Haus erspart den Zimmermann.", "家中备有斧头，便省得请木匠。", "Friedrich Schiller（弗里德里希·席勒）"],
["Es kann der Frömmste nicht im Frieden bleiben, wenn es dem bösen Nachbar nicht gefällt.", "若恶邻不容，再虔诚的人也无法安宁度日。", "Friedrich Schiller（弗里德里希·席勒）"],
["Wer mit Ungeheuern kämpft, mag zusehn, dass er nicht dabei zum Ungeheuer wird.", "与怪物搏斗的人，要当心自己不要因此也变成怪物。", "Friedrich Nietzsche（弗里德里希·尼采）"],
["Der Krug geht so lange zum Brunnen, bis er bricht.", "常在河边走，哪有不湿鞋。（水罐老往泉边提，总有一天要摔碎。）", "Deutsches Sprichwort（德国谚语）"],
["Erfahrung heißt gar nichts. Man kann seine Sache auch 35 Jahre schlecht machen.", "经验说明不了什么。一个人可能把同一件事情搞砸 35 年。", "Kurt Tucholsky（库尔特·图霍尔斯基）"],
["Sprache ist eine Waffe, haltet sie scharf.", "语言是武器，请保持它的锋利。", "Kurt Tucholsky（库尔特·图霍尔斯基）"],
["Aus so krummem Holze, als woraus der Mensch gemacht ist, kann nichts ganz Gerades gezimmert werden.", "人是由如此弯曲的木材造成的，用它造不出任何完全笔直的东西。", "Immanuel Kant（伊曼努尔·康德）"],
["Wir sind mit dem Unsichtbaren näher als mit dem Sichtbaren verbunden.", "我们与不可见之物的联系，比与可见之物更紧密。", "Novalis（诺瓦利斯）"],
["Sicher ist, dass nichts sicher ist. Selbst das nicht.", "唯一确定的是没有什么是确定的，连这句话也不确定。", "Joachim Ringelnatz (zugeschrieben)（约阿希姆·林格尔纳茨（据传））"],
["Die Politik bedeutet ein starkes langsames Bohren von harten Brettern mit Leidenschaft und Augenmaß zugleich.", "政治意味着同时凭借激情与分寸感，用力而缓慢地钻透坚硬的木板。（出自《以政治为业》）", "Max Weber（马克斯·韦伯）"],
["Hiersein ist herrlich.", "能存在于此，便是极好的。", "Rainer Maria Rilke（莱纳·玛利亚·里尔克）"],
["Dort, wo man Bücher verbrennt, verbrennt man auch am Ende Menschen.", "在焚书的地方，最终也会焚人。", "Heinrich Heine（海因里希·海涅）"],
["Jeder Mensch hält die Grenzen seines eigenen Gesichtsfeldes für die Grenzen der Welt.", "每个人都将自己视野的尽头，当作世界的尽头。", "Arthur Schopenhauer（亚瑟·叔本华）"],
["Ein edler Mensch zieht edle Menschen an.", "高尚的人会吸引高尚的人。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Man muss noch Chaos in sich haben, um einen tanzenden Stern gebären zu können.", "一个人内心里必须还有混乱，才能诞生出舞动的星星。", "Friedrich Nietzsche（弗里德里希·尼采）"],
["Gegen große Vorzüge eines anderen gibt es kein Rettungsmittel als die Liebe.", "面对他人的巨大长处，除了爱，别无补救之法。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Selig sind die Vergesslichen, denn sie werden auch mit ihren Dummheiten fertig.", "健忘者有福了，因为他们连自己的蠢事也能放下。", "Friedrich Nietzsche（弗里德里希·尼采）"],
["Wer die Wahrheit nicht weiß, der ist bloß ein Dummkopf. Aber wer sie weiß und sie eine Lüge nennt, der ist ein Verbrecher.", "不知道真相的人只是傻瓜；但知道真相却称之为谎言的人，就是罪犯。", "Bertolt Brecht（贝托尔特·布莱希特）"],
["Das Schicksal des Menschen ist der Mensch.", "人的命运就是人。（人的命运取决于人自己。）", "Bertolt Brecht（贝托尔特·布莱希特）"],
["Toren und gescheite Leute sind gleich unschädlich. Nur die Halbnarren und Halbweisen, das sind die gefährlichsten.", "傻瓜和聪明人同样无害。唯有半傻不傻、半智不智的人，才是最危险的。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Die Menschen, denen wir eine Stütze sind, geben uns den Halt im Leben.", "那些被我们支撑的人，恰恰给了我们生活的依靠。", "Marie von Ebner-Eschenbach（玛丽·冯·埃布纳-埃申巴赫）"],
["Wer nicht mehr liebt und nicht mehr irrt, der lasse sich begraben.", "不再去爱、不再犯错的人，不如就此长眠吧。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Es hört doch jeder nur, was er versteht.", "每个人终究只能听到自己能理解的东西。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Was man nicht versteht, besitzt man nicht.", "凡是你未曾理解的事物，你都不曾真正拥有。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Zwei Seelen wohnen, ach! in meiner Brust.", "唉！有两个灵魂栖息在我的胸膛里。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Wenn man alle Gesetze studieren sollte, so hätte man gar keine Zeit, sie zu übertreten.", "如果人要去把所有的法律都研究透，那就根本没时间去触犯它们了。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Der Mensch ist, was er als Mensch sein soll, erst durch die Bildung.", "人唯有通过教化，才能成为他作为人应当成为的样子。", "Georg Wilhelm Friedrich Hegel (zugeschrieben)（格奥尔格·威廉·弗里德里希·黑格尔（据传））"],
["Die dümmsten Bauern ernten die dicksten Kartoffeln.", "傻人有傻福。（最笨的农民种出最大的土豆。）", "Deutsches Sprichwort（德国谚语）"],
["Ein jeder lernt nur, was er lernen kann.", "每个人只能学会他能学会的东西。（出自《浮士德》第一部）", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Wer hoch steigt, kann tief fallen.", "爬得越高，摔得越重。", "Deutsches Sprichwort（德国谚语）"],
["Von einem gewissen Punkt an gibt es keine Rückkehr mehr. Dieser Punkt ist zu erreichen.", "从某一点开始，就再也没有回头路了。这一点是可以达到的。（ist zu erreichen 亦可理解为“必须达到”）", "Franz Kafka（弗朗茨·卡夫卡）"],
["Der Ton macht die Musik.", "说话的语气决定效果。（音调决定了音乐。）", "Deutsches Sprichwort（德国谚语）"],
["Angst verleiht Flügel.", "恐惧让人插上翅膀。（人一害怕就跑得飞快。）", "Deutsches Sprichwort（德国谚语）"],
["Eine Hand wäscht die andere.", "互惠互利。（一只手洗另一只手。）", "Deutsches Sprichwort（德国谚语）"],
["Eigentlich lernen wir nur von den Büchern, die wir nicht beurteilen können.", "实际上，我们只能从那些我们无法评判的书里学到东西。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Es bildet ein Talent sich in der Stille, sich ein Charakter in dem Strom der Welt.", "才华在静谧中养成，品格在世事的洪流中铸就。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Jedenfalls bin ich überzeugt, dass der Alte nicht würfelt.", "无论如何，我确信那位“老头子”（指上帝）是不掷骰子的。（原信为 dass der nicht würfelt，der 承前文 der Alte 而省略）", "Albert Einstein（阿尔伯特·爱因斯坦）"],
["Was vernünftig ist, das ist wirklich; und was wirklich ist, das ist vernünftig.", "凡是合理的就是现实的，凡是现实的就是合理的。", "Georg Wilhelm Friedrich Hegel（格奥尔格·威廉·弗里德里希·黑格尔）"],
["Wer fertig ist, dem ist nichts recht zu machen; ein Werdender wird immer dankbar sein.", "已经定型的人，怎么做都难让他满意；尚在成长的人，永远心怀感激。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Wer Visionen hat, sollte zum Arzt gehen.", "有愿景的人，应该去看医生。（Visionen 兼有“愿景”和“幻觉”之意，一语双关）", "Helmut Schmidt (zugeschrieben)（赫尔穆特·施密特（据传））"],
["Kein Mensch muss müssen.", "没有人必须“必须”。", "Gotthold Ephraim Lessing（戈特霍尔德·埃弗拉伊姆·莱辛）"],
["Der Schwache zweifelt vor der Entscheidung; der Starke danach.", "弱者在决断前怀疑，强者在决断后怀疑。", "Karl Kraus（卡尔·克劳斯）"],
["Ein gutes Gewissen ist ein sanftes Ruhekissen.", "问心无愧便是最好的安眠药。（好良心是柔软的安息枕。）", "Deutsches Sprichwort（德国谚语）"],
["Das Leben ist kein Ponyhof.", "生活不是游乐场。（生活不是处处轻松的。）", "Deutsches Sprichwort（德国谚语）"],
["Der größte Feind des Rechts ist das Vorrecht.", "权利最大的敌人是特权。（Recht 与 Vorrecht 构成文字游戏）", "Marie von Ebner-Eschenbach（玛丽·冯·埃布纳-埃申巴赫）"],
["Wenn die Zeit kommt, in der man könnte, ist die vorüber, in der man kann.", "等到有机会做的时候，有能力做的时候却已经过去了。", "Marie von Ebner-Eschenbach（玛丽·冯·埃布纳-埃申巴赫）"],
["Sobald du dir vertraust, sobald weißt du zu leben.", "你只要一相信自己，立刻就懂得了如何生活。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Wer A sagt, der muss nicht B sagen. Er kann auch erkennen, dass A falsch war.", "说了 A 的人未必非得说 B，他也可以承认 A 原本就是错的。", "Bertolt Brecht（贝托尔特·布莱希特）"],
["Wer den Pfennig nicht ehrt, ist des Talers nicht wert.", "不把一分钱当回事的人，也不配拥有一大笔钱。", "Deutsches Sprichwort（德国谚语）"],
["Mit den Wölfen muss man heulen.", "随波逐流。（与狼同处，就得跟着嚎叫。）", "Deutsches Sprichwort（德国谚语）"],
["Man sollte nicht aus einer Mücke einen Elefanten machen.", "不要小题大做。（别把蚊子夸大成大象。）", "Deutsches Sprichwort（德国谚语）"],
["Wer zuletzt lacht, lacht am besten.", "谁笑到最后，谁笑得最好。", "Deutsches Sprichwort（德国谚语）"],
["Morgenstund hat Gold im Mund.", "早起的鸟儿有虫吃。（清晨的时光口含黄金。）", "Deutsches Sprichwort（德国谚语）"],
["Es ist nicht wahr, dass die kürzeste Linie immer die gerade ist.", "最短的线并不总是直线。（出自《论人类的教育》）", "Gotthold Ephraim Lessing（戈特霍尔德·埃弗拉伊姆·莱辛）"],
["Wer zwei Hasen jagt, fängt keinen.", "同时追两只兔子，最终一只也抓不到。", "Deutsches Sprichwort（德国谚语）"],
["Gleich und gleich gesellt sich gern.", "物以类聚，人以群分。", "Deutsches Sprichwort（德国谚语）"],
["Der Frieden ist nicht alles, aber alles ist ohne den Frieden nichts.", "和平并非一切，但没有和平便失去了一切。", "Willy Brandt（维利·勃兰特）"],
["Es gehört oft mehr Mut dazu, seine Meinung zu ändern, als ihr treu zu bleiben.", "很多时候，改变自己的观点比坚持己见需要更大的勇气。", "Friedrich Hebbel (zugeschrieben)（弗里德里希·黑贝尔（据传））"],
["Man muss das Gute tun, damit es in der Welt ist.", "人必须去行善，善意才会存在于这个世界上。", "Marie von Ebner-Eschenbach (zugeschrieben)（玛丽·冯·埃布纳-埃申巴赫（据传））"],
["Was die Erfahrung aber und die Geschichte lehren, ist dieses, dass Völker und Regierungen niemals etwas aus der Geschichte gelernt haben.", "然而，经验和历史教给我们的却是：各民族和各国政府从未从历史中学到任何东西。", "Georg Wilhelm Friedrich Hegel（格奥尔格·威廉·弗里德里希·黑格尔）"],
["Geteilte Freude ist doppelte Freude, geteiltes Leid ist halbes Leid.", "共享快乐，快乐加倍；分担痛苦，痛苦减半。", "Deutsches Sprichwort（德国谚语）"],
["Viele Hände machen der Arbeit ein schnelles Ende.", "人多干活快。（人多力量大。）", "Deutsches Sprichwort（德国谚语）"],
["Ein Pessimist ist ein Mensch, der sich über schlechte Erfahrungen freut, weil sie ihm recht geben.", "悲观主义者就是那种为糟糕经历感到高兴的人，因为这证明他是对的。", "Heinz Rühmann (zugeschrieben)（海因茨·吕曼（据传））"],
["Humor ist keine Gabe des Geistes, er ist eine Gabe des Herzens.", "幽默不是理智的天赋，而是心灵的天赋。", "Ludwig Börne（路德维希·伯尔内）"],
["Wer den Schaden hat, braucht für den Spott nicht zu sorgen.", "吃了亏的人，从来不缺别人的嘲笑。", "Deutsches Sprichwort（德国谚语）"],
["Was man von der Minute ausgeschlagen, gibt keine Ewigkeit zurück.", "你从那一分钟里推开的东西，永恒也不会还给你。", "Friedrich Schiller（弗里德里希·席勒）"],
["Niemand ist mehr Sklave, als der sich für frei hält, ohne es zu sein.", "没有谁比那些自以为自由却实际并不自由的人更像是奴隶。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Stille Wasser sind tief.", "静水流深。", "Deutsches Sprichwort（德国谚语）"],
["Was man nicht weiß, das eben brauchte man, und was man weiß, kann man nicht brauchen.", "不知道的，恰恰用得着；知道的，偏偏用不上。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Jeder Mensch ist ein Abgrund; es schwindelt einem, wenn man hinabsieht.", "每个人都是一道深渊，往下看时，会让人头晕目眩。", "Georg Büchner（格奥尔格·毕希纳）"],
["Es gibt nichts Stilleres als eine geladene Kanone.", "世上没有什么比一门上好膛的大炮更安静的了。", "Heinrich Heine (zugeschrieben)（海因里希·海涅（据传））"],
["Ein Kompromiss ist die Kunst, einen Kuchen so zu teilen, dass jeder meint, er habe das größte Stück bekommen.", "妥协就是一种把蛋糕切得让每个人都以为自己分到了最大那一块的艺术。", "Ludwig Erhard (zugeschrieben)（路德维希·艾哈德（据传））"],
["Glück und Glas, wie leicht bricht das.", "运气犹如玻璃，何其容易破碎。", "Deutsches Sprichwort（德国谚语）"],
["Wenn der Berg nicht zum Propheten kommt, muss der Prophet zum Berge gehen.", "山不就我，我来就山。", "Deutsches Sprichwort（德国谚语）"],
["Der Charakter ruht auf der Persönlichkeit, nicht auf den Talenten.", "品格建立在人格基础之上，而非取决于才华。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Durch nichts bezeichnen die Menschen mehr ihren Charakter als durch das, was sie lächerlich finden.", "要看清一个人的品格，没有什么比观察他觉得什么东西可笑更准确的了。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Denn ich bin ein Mensch gewesen, und das heißt ein Kämpfer sein.", "因为我曾是一个人，而这意味着做一名战士。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Die Einsamkeit ist das Los aller hervorragenden Geister.", "孤独是所有杰出精神的宿命。", "Arthur Schopenhauer（亚瑟·叔本华）"],
["Gott ist tot! Gott bleibt tot! Und wir haben ihn getötet!", "上帝死了！上帝永远死了！是我们杀死了他！", "Friedrich Nietzsche（弗里德里希·尼采）"],
["Die Religion ist der Seufzer der bedrängten Kreatur... sie ist das Opium des Volkes.", "宗教是受压迫生灵的叹息……它是人民的鸦片。", "Karl Marx（卡尔·马克思）"],
["Die Philosophen haben die Welt nur verschieden interpretiert; es kommt aber darauf an, sie zu verändern.", "哲学家们只是用不同的方式解释世界，而问题在于改变世界。", "Karl Marx（卡尔·马克思）"],
["Mit Geduld und Spucke fängt man eine Mücke.", "只要有耐心，铁杵磨成针。（用耐心和口水就能抓住蚊子。）", "Deutsches Sprichwort（德国谚语）"],
["Wo ein Wille ist, ist auch ein Weg.", "有志者，事竟成。", "Deutsches Sprichwort（德国谚语）"],
["Wie gewonnen, so zerronnen.", "来得容易，去得也快。", "Deutsches Sprichwort（德国谚语）"],
["Wer fremde Sprachen nicht kennt, weiß nichts von seiner eigenen.", "不懂外语的人，对自己的母语也一无所知。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Grau, teurer Freund, ist alle Theorie, und grün des Lebens goldner Baum.", "亲爱的朋友，一切理论都是灰色的，唯有生命的金色之树常青。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Das Ewig-Weibliche zieht uns hinan.", "永恒的女性，引领我们向上。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Der Gescheitere gibt nach! Eine traurige Wahrheit; sie begründet die Weltherrschaft der Dummheit.", "“聪明人让步！”——这是一个可悲的事实，它奠定了愚蠢对世界的统治。", "Marie von Ebner-Eschenbach（玛丽·冯·埃布纳-埃申巴赫）"],
["Man ist so alt, wie man sich fühlt.", "人不觉老，便是不老。（人觉得多年轻就有多年轻。）", "Deutsches Sprichwort（德国谚语）"],
["Das also war des Pudels Kern!", "原来这才是事情的真相！（原来这就是卷毛狗的内核！——出自《浮士德》）", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Wenn einer keine Angst hat, hat er keine Phantasie.", "一个人如果从不知畏惧，那他一定毫无想象力。", "Erich Kästner（埃里希·凯斯特纳）"],
["Wir hoffen immer, und in allen Dingen ist besser hoffen als verzweifeln.", "我们总是心怀希望，而在任何事情上，抱有希望总胜过绝望。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Alle großen Ideen scheitern an den Leuten.", "所有伟大的构想，最终都败在人身上。", "Bertolt Brecht (zugeschrieben)（贝托尔特·布莱希特（据传））"],
["Wer das erste Knopfloch verfehlt, kommt mit dem Zuknöpfen nicht zu Rande.", "第一粒纽扣若扣错了，这件衣服也就扣不好了。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Der Wahn ist kurz, die Reu ist lang.", "迷狂转瞬即逝，悔恨却绵绵无期。", "Friedrich Schiller（弗里德里希·席勒）"],
["Der Reichtum gleicht dem Seewasser: je mehr man davon trinkt, desto durstiger wird man.", "财富就像海水，喝得越多，越是口渴。", "Arthur Schopenhauer（亚瑟·叔本华）"],
["Wer gar zu viel bedenkt, wird wenig leisten.", "顾虑太多的人，成就必然有限。", "Friedrich Schiller（弗里德里希·席勒）"],
["Der Mensch ist, was er isst.", "人如其食。", "Ludwig Feuerbach（路德维希·费尔巴哈）"],
["Alles Vergängliche ist nur ein Gleichnis.", "一切消逝的事物，不过是一种象征。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Wir erschrecken über unsere eigenen Sünden, wenn wir sie an anderen erblicken.", "当我们在别人身上瞥见自己的罪恶时，总会感到惊恐。", "Johann Wolfgang von Goethe (zugeschrieben)（约翰·沃尔夫冈·冯·歌德（据传））"],
["Ein Mensch kann zwar tun, was er will, aber nicht wollen, was er will.", "人虽然能做他想做的事，却不能决定自己想要什么。", "Arthur Schopenhauer (nach Einstein)（亚瑟·叔本华（据爱因斯坦转述））"],
["Der kluge Mann baut vor.", "聪明人未雨绸缪。（出自《威廉·退尔》）", "Friedrich Schiller（弗里德里希·席勒）"],
["Man muss das Eisen schmieden, solange es heiß ist.", "趁热打铁。", "Deutsches Sprichwort（德国谚语）"],
["Von der Stirne heiß rinnen muss der Schweiß, soll das Werk den Meister loben.", "滚烫的汗水须从额头淌下，作品方能为匠师增光。（出自《钟之歌》）", "Friedrich Schiller（弗里德里希·席勒）"],
["Kleine Geschenke erhalten die Freundschaft.", "小礼物维系友谊。", "Deutsches Sprichwort（德国谚语）"],
["Keine Grenze verlockt mehr zum Schmuggel als die Altersgrenze.", "没有哪条界限比年龄线更让人想偷偷越过。（Grenze 兼指国界与界限，Schmuggel 指走私，一语双关）", "Robert Musil（罗伯特·穆齐尔）"],
["Zu vollenden ist nicht die Sache des Schülers, es ist genug, wenn er sich übt.", "完成作品并不是学生的事，只要在练习，就足够了。（出自《威廉·迈斯特的学习时代》）", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Der bestirnte Himmel über mir und das moralische Gesetz in mir.", "头顶璀璨的星空，以及我心中的道德法则。", "Immanuel Kant（伊曼努尔·康德）"],
["Wer immer strebend sich bemüht, den können wir erlösen.", "凡是不断努力进取的人，我们都能将他救赎。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Lass die Leute reden und die Hunde bellen.", "随人去说，任狗去叫。", "Deutsches Sprichwort（德国谚语）"],
["Leicht beieinander wohnen die Gedanken, doch hart im Raume stoßen sich die Sachen.", "思想可以轻松地比邻而居，事物却在现实空间里激烈碰撞。", "Friedrich Schiller（弗里德里希·席勒）"],
["Wir leben alle unter dem gleichen Himmel, aber wir haben nicht alle den gleichen Horizont.", "我们都生活在同一片天空下，但并非每个人都有同样的眼界。（Horizont 兼指“地平线”与“眼界”，一语双关）", "Konrad Adenauer (zugeschrieben)（康拉德·阿登纳（据传））"],
["Alle Vorurteile kommen aus den Eingeweiden.", "所有的偏见都源于人的肠胃。", "Friedrich Nietzsche（弗里德里希·尼采）"],
["Wovon man nicht sprechen kann, darüber muss man schweigen.", "对于不可言说之事，必须保持沉默。", "Ludwig Wittgenstein（路德维希·维特根斯坦）"],
["Je planmäßiger die Menschen vorgehen, desto wirksamer trifft sie der Zufall.", "人们行事越是周密计划，偶然就越有效地击中他们。", "Friedrich Dürrenmatt（弗里德里希·迪伦马特）"],
["Toleranz sollte eigentlich nur eine vorübergehende Gesinnung sein: Sie muss zur Anerkennung führen.", "宽容本应仅仅是一种过渡的心态：它必须通向认可。", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Jeder Topf findet seinen Deckel.", "每个人总能找到适合自己的伴侣。（每个锅都能找到自己的盖子。）", "Deutsches Sprichwort（德国谚语）"],
["Jedes Naturgesetz, das sich offenbart, lässt ein höheres, noch unaufgeklärtes ahnen.", "揭开的每一条自然法则，都在暗示着一条尚未被探明的高等法则。", "Alexander von Humboldt (zugeschrieben)（亚历山大·冯·洪堡（据传））"],
["Wahrer Beruf für jeden war nur das eine: zu sich selbst zu kommen.", "每个人真正的天职只有一个：走向自己。", "Hermann Hesse（赫尔曼·黑塞）"],
["Nur der ist froh, der geben mag.", "唯有乐于给予的人，才是真正快乐的。（出自《浮士德》第一部“城门前”，原为乞丐讨钱时的唱词）", "Johann Wolfgang von Goethe（约翰·沃尔夫冈·冯·歌德）"],
["Jeder Mensch erfindet sich früher oder später eine Geschichte, die er für sein Leben hält.", "每个人迟早都会编造出一个故事，并将其当作自己的一生。", "Max Frisch（马克斯·弗里施）"],
["Der kürzeste Weg zu sich selbst führt um die Welt herum.", "通往自我的最短道路，是环绕世界一周。", "Hermann Keyserling（赫尔曼·凯泽林）"],
["Ein Buch muss die Axt sein für das gefrorene Meer in uns.", "一本书必须是能劈开我们心中冰封之海的利斧。", "Franz Kafka（弗朗茨·卡夫卡）"],
["Der Mensch ist ein Seil, geknüpft zwischen Tier und Übermensch – ein Seil über einem Abgrunde.", "人是一根系在动物与超人之间的绳索——一根悬于深渊之上的绳索。", "Friedrich Nietzsche（弗里德里希·尼采）"],
];
